version: "3"
services:
  client:
    image: mikenewxyz/absurd-quiz-app-client:1.1
    environment:
      - SERVER_URL=http://localhost:3201
    restart: unless-stopped
    ports:
      - 3200:80
    networks:
      - app_network
  server:
    image: mikenewxyz/absurd-quiz-app-server:1.0
    environment:
      - PORT=81
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    ports:
      - 3201:81
    networks:
      - app_network
networks:
  app_network: null