version: "3"
services:
  client:
    build:
      context: ./client
    environment:
      - SERVER_URL=http://localhost:3001
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - app_network
  server:
    build:
      context: ./server
      args:
        - PORT=81
        - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    ports:
      - "3001:81"
    networks:
      - app_network
networks:
  app_network: